version: 2

models:
  - name: marts_revenue_daily
    description: "Daily revenue KPI mart derived from int_orders_enriched."
    columns:
      - name: order_date
        description: "Calendar date for daily aggregation."
        tests:
          - not_null
          - unique

      - name: orders
        description: "Distinct orders per day."
        tests:
          - not_null

      - name: customers
        description: "Distinct customers per day."
        tests:
          - not_null

      - name: units
        description: "Total units sold per day."
        tests:
          - not_null

      - name: revenue
        description: "Daily revenue computed as quantity * price."
        tests:
          - not_null

      - name: aov
        description: "Average order value (revenue / orders)."

      - name: revenue_per_customer
        description: "Revenue per customer (revenue / customers)."
      - name: marts_revenue_by_category_daily
        description: "Daily revenue KPIs broken out by product category."
        columns:
      - name: order_date
        description: "Calendar date for daily aggregation."
        tests:
          - not_null

      - name: category
        description: "Product category."
        tests:
          - not_null

      - name: revenue
        description: "Daily revenue per category."
        tests:
          - not_null
      - name: marts_customer_ltv
        description: "Customer lifetime value metrics derived from order history."
        columns:
      - name: customer_id
        description: "Unique customer identifier."
        tests:
          - not_null
          - unique

      - name: lifetime_revenue
        description: "Total revenue generated by the customer."
        tests:
          - not_null

      - name: lifetime_orders
        description: "Total number of orders placed by the customer."
        tests:
          - not_null
      
      - name: lifetime_units
        description: "Total units purchased by the customer across their lifetime."
        tests:
          - not_null


      - name: first_order_date
        description: "Date of the customer's first order."

      - name: last_order_date
        description: "Date of the customer's most recent order."

      - name: lifetime_aov
        description: "Average order value across the customer's lifetime."

      - name: marts_top_products_daily
        description: "Top 10 products per day ranked by revenue."
        columns:
      
      - name: order_date
        description: "Calendar date for daily ranking."
        tests:
          - not_null

      - name: revenue_rank
        description: "Rank of the product by revenue for the day (1 = highest)."
        tests:
          - not_null

      - name: product_id
        description: "Unique product identifier."
        tests:
          - not_null

      - name: revenue
        description: "Daily revenue for the product."
        tests:
          - not_null


